# ansible-playbook dogmonit.yml --extra-vars "host=<hostname>" "api_key=<API key>"
---
- hosts:  "{{ host | default('web') }}"
  user: root #??
  tasks:
#    - name: Installing datadog-agent
#
    - name: Install step 1
      command: "wget https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh"
    - name: Install 12
      command: mv ./install_agent.sh /tmp/
    - name: Install step 2
      command: chmod 700 /tmp/install_agent.sh
    - name: Install step 3      
      command: sed -i -e 's/set -e/DD_API_KEY=05a6f7e847cc00674826ddfeb7593ed7\nset -e/' /tmp/install_agent.sh
    - name: starting script
      command: /tmp/install_agent.sh
    - name: Copying check files (ucs_fi.py)
      copy:
        src: ./ucs_fi.py
        dest: /etc/dd-agent/checks.d/
    - name: Copying check files (ucs-fault.py)
      copy:
        src: ./ucs-faults.py
        dest: /etc/dd-agent/checks.d/
    - name: Copying configuration files (ucs_fi.yaml)
      copy:
        src: ./ucs_fi.yaml
        dest: /etc/dd-agent/conf.d/
    - name: Copying configuration files (tcp_check.yaml)
      copy:
        src: ./tcp_check.yaml
        dest: /etc/dd-agent/conf.d/

...

